services:
  - type: web
    name: consilium
    runtime: node
    buildCommand: npm run build
    startCommand: node back/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
