CREATE TABLE IF NOT EXISTS deputes (
    id                              VARCHAR(20)     PRIMARY KEY,
    legislature                     INTEGER         NOT NULL,
    civ                             VARCHAR(10),
    nom                             VARCHAR(100)    NOT NULL,
    prenom                          VARCHAR(100)    NOT NULL,
    ville_naissance                 VARCHAR(100),
    naissance                       DATE,
    age                             INTEGER,
    groupe                          VARCHAR(200),
    groupe_abrev                    VARCHAR(20),
    departement_nom                 VARCHAR(100),
    departement_code                VARCHAR(10),
    circo                           INTEGER,
    date_prise_fonction             DATE,
    job                             VARCHAR(200),
    mail                            VARCHAR(200),
    twitter                         VARCHAR(100),
    facebook                        VARCHAR(100),
    website                         VARCHAR(200),
    nombre_mandats                  INTEGER,
    experience_depute               VARCHAR(50),
    score_participation             DECIMAL(6, 4),
    score_participation_specialite  DECIMAL(6, 4),
    score_loyaute                   DECIMAL(6, 4),
    score_majorite                  DECIMAL(6, 4),
    date_maj                        DATE,
    created_at                      TIMESTAMP       DEFAULT NOW(),
    updated_at                      TIMESTAMP       DEFAULT NOW()
);
